[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "cdiscountapi"
author = "ZIBOURA Mathilde, RABOIS Damien"
author-email = "mathilde.ziboura@abc-culture.fr"
classifiers = ["License :: OSI Approved :: MIT License"]

requires = [ 
    "requests==2.21.0",
    "requests_mock==1.5.2",
    "zeep==3.3.1",
    "dicttoxml==1.7.4",
    "PyYAML==5.1",
]

requires-python = ">=3.6"

[tool.flit.metadata.requires-extra]
test = [
    "pytest==4.3.1",
    "vcrpy==2.0.1",
    "pytest-vcr==1.0.1",
    "coverage==4.5.3",
    "pytest-cov==2.6.1",
]
dev = [
    "pdbpp",
    "ipython",
    "konch",
]
doc = ["sphinx", "sphinx-nameko-theme"]

[tool.black]
line-length = 88
